normal_mapping = {
    "AC": "opponent_corners",
    "AF": "opponent_fouls",
    "AHCh": "ahch",
    "AwayTeam": "opponent",
    "AHh": "team_market_size_of_handicap",
    "AR": "opponent_red_cards",
    "AS": "opponent_shots",
    "AST": "opponent_shots_on_target",
    "AY": "opponent_yellow_cards",
    "Avg<2.5": "market_average_under_2.5_goals",
    "Avg>2.5": "market_average_over_2.5_goals",
    "AvgA": "market_average_opponent_win_odds",
    "AvgAHA": "market_average_asian_handicap_opponent_odds",
    "AvgAHH": "market_average_asian_handicap_team_odds",
    "AvgC<2.5": "market_average_c_under_2.5_goals",
    "AvgC>2.5": "market_average_c_over_2.5_goals",
    "AvgCA": "market_average_ca_odds",
    "AvgCAHA": "AvgCAHA",
    "AvgCAHH": "AvgCAHH",
    "AvgCD": "AvgCD",
    "AvgCH": "AvgCH",
    "AvgD": "market_average_draw_win_odds",
    "AvgH": "market_average_team_win_odds",
    "Team": "team",
    "B365<2.5": "b365_under_2.5_goals",
    "B365>2.5": "b365_over_2.5_goals",
    "B365A": "b365_opponent_win_odds",
    "B365AHA": "b365_asian_handicap_opponent_odds",
    "B365AHH": "b365_asian_handicap_team_odds",
    "B365C<2.5": "b365c<2.5",
    "B365C>2.5": "b365c>2.5",
    "B365CA": "b365ca",
    "B365CAHA": "b365caha",
    "B365CAHH": "b365cahh",
    "B365CD": "b365cd",
    "B365CH": "b365ch",
    "B365D": "b365_draw_odds",
    "B365H": "b365_team_win_odds",
    "BSA": "blue_square_opponent_win_odds",
    "BSD": "blue_square_draw_odds",
    "BSH": "blue_scale_team_win_odds",
    "BWA": "bet_and_win_opponent_win_odds",
    "BWCA": "bet_and_win_ca",
    "BWCD": "bet_and_win_cd",
    "BWCH": "bet_and_win_ch",
    "BWD": "bet_and_win_draw_odds",
    "BWH": "bet_and_win_team_win_odds",
    "Bb1X2": "number_of_betbrain_bookmakers_used_to_calculate_match_odds_avg_and_max",
    "BbAH": "number_of_betbrain_bookmakers_used_to_asian_handicap_avg_and_max",
    "BbAHh": "betbrain_size_of_handicap_team",
    "BbAv<2.5": "betbrain_avg_under_2.5_goals",
    "BbAv>2.5": "betbrain_ag_over_2.5_goals",
    "BbAvA": "betbrain_avg_opponent_win_odds",
    "BbAvAHA": "betbrain_avg_asian_handicap_opponent_odds",
    "BbAvAHH": "betbrain_avg_asian_handicap_team_odds",
    "BbAvD": "betbrain_avg_draw_win_odds",
    "BbAvH": "betbrain_avg_team_win_odds",
    "BbMx<2.5": "betbrain_max_under_2.5",
    "BbMx>2.5": "betbrain_max_over_2.5",
    "BbMxA": "betbrain_max_opponent_win_odds",
    "BbMxAHA": "betbrain_max_asian_handicap_opponent_odds",
    "BbMxAHH": "betbrain_max_asian_handicap_team_odds",
    "BbMxD": "betbrain_max_draw_team_odds",
    "BbMxH": "betbrain_max_team_win_odds",
    "BbOU": "number_of_betbrain_bookmakers_used_to_calculate_over_under_2.5_goals_total_goals_avg_and_max",
    "Date": "date",
    "Div": "division",
    "FTAG": "full_time_opponent_goals",
    "FTHG": "full_time_team_goals",
    "FTR": "full_time_result",
    "GBA": "gamebookers_opponent_odds",
    "GBD": "gamebookers_draw_odds",
    "GBH": "gamebookers_team_odds",
    "HC": "team_corners",
    "HF": "team_fouls_committed",
    "HR": "team_red_cards",
    "HS": "team_shots",
    "HST": "team_shots_on_target",
    "HTAG": "half_time_opponent_goals",
    "HTHG": "half_time_team_goals",
    "HTR": "half_time_result",
    "HY": "team_yellow_cards",
    "HomeTeam": "team",
    "IWA": "interwetten_opponent_win_odds",
    "IWCA": "interwetten_ca",
    "IWCD": "interwetten_cd",
    "IWCH": "interwetten_ch",
    "IWD": "interwetten_draw_odds",
    "IWH": "interwetten_team_win_odds",
    "LBA": "ladbrokes_opponent_win_odds",
    "LBD": "ladbrokes_draw_odds",
    "LBH": "ladbrokes_team_win_odds",
    "Max<2.5": "market_max_under_2.5_goals",
    "Max>2.5": "market_max_over_2.5_goals",
    "MaxA": "market_max_opponent_win_odds",
    "MaxAHA": "market_max_asian_handicap_opponent_odds",
    "MaxAHH": "market_max_asian_handicap_team_odds",
    "MaxC<2.5": "market_max_c_under_2.5_goals",
    "MaxC>2.5": "market_max_c_over_2.5_goals",
    "MaxCA": "market_max_ca",
    "MaxCAHA": "market_max_caha",
    "MaxCAHH": "market_max_cahh",
    "MaxCD": "market_max_cd",
    "MaxCH": "market_max_ch",
    "MaxD": "market_max_draw_win_odds",
    "MaxH": "market_max_team_win_odds",
    "P<2.5": "pinnacle_under_2.5_goals",
    "P>2.5": "pinnacle_over_2.5_goals",
    "PAHA": "pinnacle_asian_handicap_opponent_win_odds",
    "PAHH": "pinnacle_asian_handicap_team_win_odds",
    "PC<2.5": "pc_under_2.5",
    "PC>2.5": "pc_over_2.5",
    "PCAHA": "pcaha",
    "PCAHH": "pcahh",
    "PSA": "pinnacle_opponent_win_odds",
    "PSCA": "psca",
    "PSCD": "pscd",
    "PSCH": "psch",
    "PSD": "pinnacle_draw_odds",
    "PSH": "pinnacle_team_win_odds",
    "Referee": "referee",
    "SBA": "sportingbet_opponent_win_odds",
    "SBD": "sportingbet_draw_odds",
    "SBH": "sportingbet_team_win_odds",
    "SJA": "stan_james_opponent_win_odds",
    "SJD": "stan_james_draw_odds",
    "SJH": "stan_james_home_odds",
    "Time": "time",
    "VCA": "vc_bet_opponent_win_odds",
    "VCCA": "vcca",
    "VCCD": "vccd",
    "VCCH": "vcch",
    "VCD": "vc_bet_draw_odds",
    "VCH": "vc_bet_team_win_odds",
    "WHA": "william_hill_opponent_win_odds",
    "WHCA": "whca",
    "WHCD": "whcd",
    "WHCH": "whch",
    "WHD": "william_hill_draw_odds",
    "WHH": "william_hill_team_win_odds",
}

reverse_mapping = {
    "AC": "team_corners",
    "AF": "team_fouls",
    "AHCh": "ahch",
    "AwayTeam": "team",
    "AHh": "opponent_market_size_of_handicap",
    "AR": "team_red_cards",
    "AS": "team_shots",
    "AST": "team_shots_on_target",
    "AY": "team_yellow_cards",
    "Avg<2.5": "market_average_under_2.5_goals",
    "Avg>2.5": "market_average_over_2.5_goals",
    "AvgA": "market_average_team_win_odds",
    "AvgAHA": "market_average_asian_handicap_team_odds",
    "AvgAHH": "market_average_asian_handicap_opponent_odds",
    "AvgC<2.5": "market_average_c_under_2.5_goals",
    "AvgC>2.5": "market_average_c_over_2.5_goals",
    "AvgCA": "market_average_ca_odds",
    "AvgCAHA": "AvgCAHA",
    "AvgCAHH": "AvgCAHH",
    "AvgCD": "AvgCD",
    "AvgCH": "AvgCH",
    "AvgD": "market_average_draw_win_odds",
    "AvgH": "market_average_opponent_win_odds",
    "Team": "opponent",
    "B365<2.5": "b365_under_2.5_goals",
    "B365>2.5": "b365_over_2.5_goals",
    "B365A": "b365_team_win_odds",
    "B365AHA": "b365_asian_handicap_team_odds",
    "B365AHH": "b365_asian_handicap_opponent_odds",
    "B365C<2.5": "b365c<2.5",
    "B365C>2.5": "b365c>2.5",
    "B365CA": "b365ca",
    "B365CAHA": "b365caha",
    "B365CAHH": "b365cahh",
    "B365CD": "b365cd",
    "B365CH": "b365ch",
    "B365D": "b365_draw_odds",
    "B365H": "b365_opponent_win_odds",
    "BSA": "blue_square_team_win_odds",
    "BSD": "blue_square_draw_odds",
    "BSH": "blue_scale_opponent_win_odds",
    "BWA": "bet_and_win_team_win_odds",
    "BWCA": "bet_and_win_ca",
    "BWCD": "bet_and_win_cd",
    "BWCH": "bet_and_win_ch",
    "BWD": "bet_and_win_draw_odds",
    "BWH": "bet_and_win_opponent_win_odds",
    "Bb1X2": "number_of_betbrain_bookmakers_used_to_calculate_match_odds_avg_and_max",
    "BbAH": "number_of_betbrain_bookmakers_used_to_asian_handicap_avg_and_max",
    "BbAHh": "betbrain_size_of_handicap_opponent",
    "BbAv<2.5": "betbrain_avg_under_2.5_goals",
    "BbAv>2.5": "betbrain_ag_over_2.5_goals",
    "BbAvA": "betbrain_avg_team_win_odds",
    "BbAvAHA": "betbrain_avg_asian_handicap_team_odds",
    "BbAvAHH": "betbrain_avg_asian_handicap_opponent_odds",
    "BbAvD": "betbrain_avg_draw_win_odds",
    "BbAvH": "betbrain_avg_opponent_win_odds",
    "BbMx<2.5": "betbrain_max_under_2.5",
    "BbMx>2.5": "betbrain_max_over_2.5",
    "BbMxA": "betbrain_max_team_win_odds",
    "BbMxAHA": "betbrain_max_asian_handicap_team_odds",
    "BbMxAHH": "betbrain_max_asian_handicap_opponent_odds",
    "BbMxD": "betbrain_max_draw_opponent_odds",
    "BbMxH": "betbrain_max_opponent_win_odds",
    "BbOU": "number_of_betbrain_bookmakers_used_to_calculate_over_under_2.5_goals_total_goals_avg_and_max",
    "Date": "date",
    "Div": "division",
    "FTAG": "full_time_team_goals",
    "FTHG": "full_time_opponent_goals",
    "FTR": "full_time_result",
    "GBA": "gamebookers_team_odds",
    "GBD": "gamebookers_draw_odds",
    "GBH": "gamebookers_opponent_odds",
    "HC": "opponent_corners",
    "HF": "opponent_fouls_committed",
    "HR": "opponent_red_cards",
    "HS": "opponent_shots",
    "HST": "opponent_shots_on_target",
    "HTAG": "half_time_team_goals",
    "HTHG": "half_time_opponent_goals",
    "HTR": "half_time_result",
    "HY": "opponent_yellow_cards",
    "HomeTeam": "opponent",
    "IWA": "interwetten_team_win_odds",
    "IWCA": "interwetten_ca",
    "IWCD": "interwetten_cd",
    "IWCH": "interwetten_ch",
    "IWD": "interwetten_draw_odds",
    "IWH": "interwetten_opponent_win_odds",
    "LBA": "ladbrokes_team_win_odds",
    "LBD": "ladbrokes_draw_odds",
    "LBH": "ladbrokes_opponent_win_odds",
    "Max<2.5": "market_max_under_2.5_goals",
    "Max>2.5": "market_max_over_2.5_goals",
    "MaxA": "market_max_team_win_odds",
    "MaxAHA": "market_max_asian_handicap_team_odds",
    "MaxAHH": "market_max_asian_handicap_opponent_odds",
    "MaxC<2.5": "market_max_c_under_2.5_goals",
    "MaxC>2.5": "market_max_c_over_2.5_goals",
    "MaxCA": "market_max_ca",
    "MaxCAHA": "market_max_caha",
    "MaxCAHH": "market_max_cahh",
    "MaxCD": "market_max_cd",
    "MaxCH": "market_max_ch",
    "MaxD": "market_max_draw_win_odds",
    "MaxH": "market_max_opponent_win_odds",
    "P<2.5": "pinnacle_under_2.5_goals",
    "P>2.5": "pinnacle_over_2.5_goals",
    "PAHA": "pinnacle_asian_handicap_team_win_odds",
    "PAHH": "pinnacle_asian_handicap_opponent_win_odds",
    "PC<2.5": "pc_under_2.5",
    "PC>2.5": "pc_over_2.5",
    "PCAHA": "pcaha",
    "PCAHH": "pcahh",
    "PSA": "pinnacle_team_win_odds",
    "PSCA": "psca",
    "PSCD": "pscd",
    "PSCH": "psch",
    "PSD": "pinnacle_draw_odds",
    "PSH": "pinnacle_opponent_win_odds",
    "Referee": "referee",
    "SBA": "sportingbet_team_win_odds",
    "SBD": "sportingbet_draw_odds",
    "SBH": "sportingbet_opponent_win_odds",
    "SJA": "stan_james_team_win_odds",
    "SJD": "stan_james_draw_odds",
    "SJH": "stan_james_home_odds",
    "Time": "time",
    "VCA": "vc_bet_team_win_odds",
    "VCCA": "vcca",
    "VCCD": "vccd",
    "VCCH": "vcch",
    "VCD": "vc_bet_draw_odds",
    "VCH": "vc_bet_opponent_win_odds",
    "WHA": "william_hill_team_win_odds",
    "WHCA": "whca",
    "WHCD": "whcd",
    "WHCH": "whch",
    "WHD": "william_hill_draw_odds",
    "WHH": "william_hill_opponent_win_odds",
}

drop_columns = [
    "ahch",
    "AvgCAHA",
    "AvgCAHH",
    "AvgCD",
    "AvgCH",
    "b365c<2.5",
    "b365c>2.5",
    "b365ca",
    "b365caha",
    "b365cahh",
    "b365cd",
    "b365ch",
    "interwetten_ca",
    "interwetten_ca",
    "interwetten_ch",
    "market_max_c_under_2.5_goals",
    "market_max_c_over_2.5_goals",
    "market_max_ca",
    "market_max_caha",
    "market_max_cahh",
    "market_max_cd",
    "market_max_ch",
    "pcaha",
    "pcahh",
    "psca",
    "pscd",
    "psch",
    "vcca",
    "vccd",
    "vcch",
    "whca",
    "whch",
]